// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Article.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home_: typeof import('./src/components/home_.vue')['default']
    Home_2_text: typeof import('./src/components/home_2_text.vue')['default']
    IndexView: typeof import('./src/components/Home/IndexView.vue')['default']
    LeftZone: typeof import('./src/components/LeftZone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideItem: typeof import('./src/components/SlideItem.vue')['default']
    SlidePage: typeof import('./src/components/SlidePage.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Text: typeof import('./src/components/Home/Text.vue')['default']
  }
}
